//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEMTK_SV
    {
        public int TT { get; set; }
        public string MSSV { get; set; }
        public string HOTEN { get; set; }
        public string MONHOC { get; set; }
        public Nullable<int> SOTC { get; set; }
        public Nullable<double> TONGKETMON { get; set; }
        public Nullable<double> TONGKETHOCKY { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
