//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM
    {
        public string MSSV { get; set; }
        public string HOTEN { get; set; }
        public string MONHOC { get; set; }
        public string LOP { get; set; }
        public string HOCKY { get; set; }
        public Nullable<int> DIEMCC { get; set; }
        public Nullable<double> DIEMTBKT { get; set; }
        public Nullable<double> DIEMTHIL1 { get; set; }
        public Nullable<double> DIEMTHIL2 { get; set; }
        public Nullable<double> DIEMTHINHAN { get; set; }
        public Nullable<double> DIEMTONGKETMON { get; set; }
        public string GHICHU { get; set; }
        public bool TRANGTHAI { get; set; }
        public int TT { get; set; }
        public string NGANH { get; set; }
    
        public virtual HOCKY HOCKY1 { get; set; }
        public virtual LOP LOP1 { get; set; }
        public virtual MONHOC MONHOC1 { get; set; }
        public virtual NGANH NGANH1 { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
