//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOANSV
    {
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> LOAITAIKHOAN { get; set; }
        public bool TRANGTHAI { get; set; }
        public int TT { get; set; }
    }
}
